name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v6
        - name: list and view file
          run: |
            echo "my first githubactions job"
            ls -lrta
            cat README.md
        - name: Generate ASCII
          run: cowsay -f dragon " run " >> op.txt
        # - name: list files
        #   run: ls
        # - name: read files
        #   run: cat README.md