name: generate ASCII artwork

on: push

jobs:
    ascii_ob:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v6
        - name: executing shell script
          run: ./script.sh

        # - name: list files
        #   run: ls
        # - name: read files
        #   run: cat README.md