name: generate ASCII artwork

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v6
        - name: list files
          run: ls -lrta
        - name: installing cowsay
          run: sudo apt-get install cowsay -y
        - name: executing cowsay
          run: cowsay -f dragon "run" >> op.txt
        - name: list files
          run: ls -lrta
        - name: sleep for 2 sec
          run: sleep 2
        - name: upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: download dragon file
            path: op.txt
    test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
        - name: download artifacts
          uses: actions/download-artifact@v4
          with:
            name: download dragon file
        - name: list files
          run: ls -lrta
        - name: sleep for 1 sec
          run: sleep 1
        - name: test files
          run: grep -i "run" op.txt   
    deploy_job:
        runs-on: ubuntu-latest
        needs: test_job
        steps:
        - name: list files
          run: ls -lrta
        - name: download artifacts
          uses: actions/download-artifact@v4
          with:
            name: download dragon file
        - name: print file
          run: cat op.txt